apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
  label:
    type: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-097b1e1c650677334


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim
  label:
    type: ebs-static pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    