kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-dynamic-claim
spec:
  storageClassName: ebs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    purpose: dynamic-ebs
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic-claim

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
spec:
  type: LoadBalancer
  selector:
    purpose: dynamic-ebs
  ports:
  - name: loadbalancer-svc
    protocol: TCP
    port: 80
    targetPort: 80
   
    

