kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: expense-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  fileSystemId: fs-04b231008db9f01ef
  basePath: "/expense"

