# apiVersion: v1
# kind: pod
# metadata:
#   name: nginx
# spec:
#   containers:
#     - name: nginx
#       image: nginx

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx