kind: Pod
apiVersion: v1
metadata: 
  name: resource-limit
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 68Mi
        limits:
          cpu: 120m
          memory: 100Mi