#refering the values from configmap
kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: course
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: trainer
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: duration