# accessing secrets from secrets.yaml
kind: Pod
apiVersion: v1
metadata:
  name: gettingsecrets
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
           name: secrets

# apiVersion: v1
# kind: Pod
# metadata:
#   name: example-pod
# spec:
#   containers:
#     - name: example-container
#       image: example-image
#       envFrom:
#         - secretRef:
#             name: my-secret