# accessing secrets from secrets.yaml
kind: Pod
apiVersion: v1
metadata:
  name: gettingsecrets
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        secretRef:
          name: secrets