kind: Service
apiVersion: v1
metadata:
  name: clusterip
spec:
  type: ClusterIP
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
  #type: ClusterIP
