kind: Service
apiVersion: v1
metadata:
  name: clusterIp
spec:
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
