kind: Service
apiVersion: v1
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
    name: nginx-svc-node-port
    protocol: TCP
    port: 80
    targetPort: 80
