kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    project: expense
    module: backend
    tier: api
spec:
  replicas: 30
  selector:
    matchLabels:
      project: expense
      module: backend
  template:
    metadata:
      labels:
        project: expense
        module: backend
    spec:
       containers:
        - name: nginx
          image: nginx
          #image: nginx:stable-perl
          #image: nginx:stable-bookworm-perl

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-1
spec:
  selector:
    project: expense
    module: backend
  ports:
  - name: nginx-svc
    protocol: TCP
    port: 80
    targetPort: 80


