kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    project: expense
    module: backend
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      module: backend
  template:
    metadata:
      labels:
        project: expense
        module: backend
    spec:
       containers:
        - name: nginx
          image: nginx
  
